# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create Env
      run: |
        echo "{{secrets.ENV_FILE}}" > .env
        echo "{{secrets.ENV_TEST_FILE}}" > .env.test

    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "./docker-compose.yml"
    - name: Generate Prisma Client
      run: |
        docker-compose exec -it app npm run prisma migrate deploy
    - name: Generate test DB
      run: docker-compose exec -it app npm run dotenv -e .env.test -- npm run prisma db push --accept-data-loss
    - name: Run tests
      run: echo docker-compose exec -it app npm run test
    - name: Stop containers
      if: always()
      run: docker-compose -f "./docker-compose.yml" down
