# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    - name: Create Env
      run: |
        echo "{{secrets.ENV_FILE}}" > .env
        echo "{{secrets.ENV_TEST_FILE}}" > .env.test

    - name: Docker compose Up
      id: docker-build
      uses: adambirds/docker-compose-action@v1.3.0
      env:
        DATABASE_URL: "{{secrets.DATABASE_URL}}"
      with:
        compose-file: "./docker-compose.yml"
        up-flags: "--env-file=./.env"
        down-flags: "--volumes"
        services: |
          app
          db
    - name: Generate Prisma Client
      id: prisma-client
      if: steps.docker-build.outcome == 'success'
      run: |
        docker-compose exec -it app npm run prisma migrate deploy
    - name: Generate test DB
      id: test-db
      if: steps.prisma-client.outcome == 'success'
      run: docker-compose exec -it app npm run dotenv -e .env.test -- npm run prisma db push --accept-data-loss
    - name: Run tests
      if: steps.test-db.outcome == 'success'
      run: docker-compose exec -it app npm run test
